### ISSUE TITLE
Secure header for SSL

### ISSUE THREAD

**Issue by MiiRaGe** [holms/ansible-balancer#2]
Hi,

Is there any plan to add security headers to make the ssl configuration more robust and inline with security good practises ?

Things such as X-Frame-Option, X-Content-Type-Options, X-XSS-Protection and even restricting to TLS v1.1/1,2 (and 1.0 for backward compatibility).

Kind Regards,
Alexis

**Comment by holms** [comment]
Hi, unless you'll show me properly working nginx virtual host configuration, I can add headers then. But this should be load balancer configuration, and not some running backend app configuration.

**Comment by MiiRaGe** [comment]
Hi,

I was thinking something following those kind of conf (excluding dhparams as it would involve another command which might be out of scope).
https://gist.github.com/plentz/6737338#file-nginx-conf

Kind Regards,
Alexis

**Comment by holms** [comment]
@MiiRaGe according to what i've read in those comments, this generator does better job than everything what's written in that gist :) https://mozilla.github.io/server-side-tls/ssl-config-generator/

Actually implementing this configuration wouldn't hurt.. Although it's hard to test it, i need to deploy 2 nodes + lb in order to test it.. but because it's from Mozilla.. I suspect this might work out of the box.
